spring:
  profiles: dev
  mail:
    username: ${emailId}
    password: ${emailPass}

url: jdbc:mysql://localhost:${port}/${dbName}
dbUserName: ${dbUserName}
dbPassword: ${dbUserPass}
driverClassName: com.mysql.cj.jdbc.Driver